baseURL: "https://numerachie.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: numarchi.e
paginate: 5
theme: PaperMod
canonifyURLs: true

params:
    homeInfoParams:
        Title: "Mimosa"
        Content: >
          Vous vous trouvez à la racine d'un projet de recherche. Errer, rencontrer, contempler et tisser seront les préceptes de ce voyage.
    hideMeta: false

menu:
  main:

    - identifier: About
      name: About
      url: /about/
      weight: 9
outputs:
    home:
        - HTML
        - RSS
        - JSON